// <auto-generated />
namespace FilmesAPI.FSharp.Migrations

open System
open FilmesAPI.FSharp.Data
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<FilmeContext>)>]
[<Migration("20220103190524_CriandoTabelaDeFilme")>]
type CriandoTabelaDeFilme() =
    inherit Migration()

    override this.Up(migrationBuilder:MigrationBuilder) =
        migrationBuilder.CreateTable(
            name = "Filmes"
            ,columns = (fun table -> 
            {|
                Id =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    ).Annotation("Sqlite:Autoincrement", true)
                Titulo =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                Genero =
                    table.Column<string>(
                        nullable = false
                        ,``type`` = "TEXT"
                    )
                Diretor =
                    table.Column<string>(
                        nullable = true
                        ,``type`` = "TEXT"
                        ,maxLength = Nullable(30)
                    )
                Duracao =
                    table.Column<int>(
                        nullable = false
                        ,``type`` = "INTEGER"
                    )
            |})
            , constraints =
                (fun table -> 
                    table.PrimaryKey("PK_Filmes", (fun x -> (x.Id) :> obj)
                    ) |> ignore
                )
        ) |> ignore


    override this.Down(migrationBuilder:MigrationBuilder) =
        migrationBuilder.DropTable(
            name = "Filmes"
            ) |> ignore


    override this.BuildTargetModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "6.0.1") |> ignore

        modelBuilder.Entity("FilmesAPI.FSharp.Models.Filme", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(0)
                |> ignore

            b.Property<string>("Diretor")
                .IsRequired(true)
                .HasMaxLength(30)
                .HasColumnType("TEXT")
                |> ignore

            b.Property<int>("Duracao")
                .IsRequired(true)
                .HasColumnType("INTEGER")
                .HasDefaultValue(0)
                |> ignore

            b.Property<string>("Genero")
                .IsRequired(true)
                .HasColumnType("TEXT")
                |> ignore

            b.Property<string>("Titulo")
                .IsRequired(true)
                .HasColumnType("TEXT")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("Filmes") |> ignore

        )) |> ignore

