// <auto-generated />
namespace FilmesAPI.FSharp.Migrations

open System
open FilmesAPI.FSharp.Data
open Microsoft.EntityFrameworkCore
open Microsoft.EntityFrameworkCore.Infrastructure
open Microsoft.EntityFrameworkCore.Metadata
open Microsoft.EntityFrameworkCore.Migrations
open Microsoft.EntityFrameworkCore.Storage.ValueConversion

[<DbContext(typeof<FilmeContext>)>]
type FilmeContextModelSnapshot() =
    inherit ModelSnapshot()

    override this.BuildModel(modelBuilder: ModelBuilder) =
        modelBuilder.HasAnnotation("ProductVersion", "6.0.1") |> ignore

        modelBuilder.Entity("FilmesAPI.FSharp.Models.Filme", (fun b ->

            b.Property<int>("Id")
                .IsRequired(true)
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER")
                .HasDefaultValue(0)
                |> ignore

            b.Property<string>("Diretor")
                .IsRequired(true)
                .HasMaxLength(30)
                .HasColumnType("TEXT")
                |> ignore

            b.Property<int>("Duracao")
                .IsRequired(true)
                .HasColumnType("INTEGER")
                .HasDefaultValue(0)
                |> ignore

            b.Property<string>("Genero")
                .IsRequired(true)
                .HasColumnType("TEXT")
                |> ignore

            b.Property<string>("Titulo")
                .IsRequired(true)
                .HasColumnType("TEXT")
                |> ignore

            b.HasKey("Id")
                |> ignore


            b.ToTable("Filmes") |> ignore

        )) |> ignore

